server:
  port: 8888
  servlet:
    context-path: /auth

spring:
  application:
    name: cloud-auth

jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: secret
  #JWT的超期限时间(1000*60*60*24*7)
  expiration: 604800000
  #JWT负载中拿到开头
  tokenHead: Bearer