server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port} #默认为：${spring.application.name}-${server.port}
    gateway:
      httpclient:
        #全局超时设置
        connect-timeout: 5000 #毫秒
        response-timeout: 5s #java.time.Duration
      #路由规则
      routes:
          #路由ID
        - id: cloud-consumer
          #uri: http://127.0.0.1:9100/ #静态目标URI,到微服务的地址
          uri: lb://cloud-consumer #动态目标URI,到微服务的地址
          #将符合的路径追加到uri后面
          predicates:
            - Path=/consumer/** #eg:http://localhost:9000/consumer/userinfo/listInfo?msg=xx
      discovery:
        locator:
          enabled: true #启用动态URI访问, 通过service-name访问. 与上面的routes里面的不冲突, 两者都可以用, eg:http://localhost:9000/cloud-consumer/consumer/userinfo/listInfo?msg=xx
          lower-case-service-id: true #使用小写服务名

management:
  endpoints:
    web:
      exposure:
        include: health, info
