server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
    gateway:
      httpclient:
        #全局超时设置
        connect-timeout: 5000 #毫秒
        response-timeout: 5s #java.time.Duration
      #路由规则
      routes:
          #路由ID
        - id: cloud-consumer
          #uri: http://127.0.0.1:9100/ #静态目标URI,到微服务的地址
          uri: lb://cloud-consumer #动态目标URI,到微服务的地址
          #将符合的路径追加到uri后面
          predicates:
            - Path=/consumer/**
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
