server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
    gateway:
      #路由规则
      routes:
        - id: cloud-consumer #路由ID
          uri: http://127.0.0.1:9100/ #目标URI,到微服务的地址
          predicates:
            - Path=/consumer/** #将符合的路径追加到uri后面

management:
  endpoints:
    web:
      exposure:
        include: health, info