server:
  port: 9091
spring:
  application:
    name: cloud-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
#        ip-address: ${spring.cloud.client.ip-address}
management:
  endpoints:
    web:
      exposure:
        include: health, info