server:
  port: 9100
  servlet:
    context-path: /consumer

spring:
  application:
    name: cloud-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path}/actuator/health
        #register-health-check: false 禁用Health检查
        #health-check-path: ${management.server.servlet.context-path}/actuator/health 单独的management.server端口
        #ip-address: ${spring.cloud.client.ip-address}
management:
  endpoints:
    web:
      exposure:
        include: health, info